spring.application.name=api-covid19

# Conexão com o PostgreSQL (porta 5431 e schema covid)
spring.datasource.url=jdbc:postgresql://localhost:5431/covid_db?currentSchema=covid
spring.datasource.username=postgres
spring.datasource.password=123@Mudar
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Hibernate / JPA
spring.jpa.properties.hibernate.default_schema=covid
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true